// Generated by extract_types.py from mozjs_sys's bindgen output.

    #[repr(C)]
    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct DispatchablePointer {
        pub ptr: u64,
    }

    pub type GetSize =
        ::std::option::Option<unsafe extern "C" fn(obj: *mut JSObject) -> usize>;

    pub type InvokeScriptPreparerHook = ::std::option::Option<
        unsafe extern "C" fn(
            global: HandleObject,
            closure: *mut ScriptEnvironmentPreparer_Closure,
        ),
    >;

    #[repr(C)]
    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct JSPrincipalsCallbacks {
        pub write: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut JSPrincipals,
                cx: *mut JSContext,
                writer: *mut JSStructuredCloneWriter,
            ) -> bool,
        >,
        pub isSystemOrAddonPrincipal:
            ::std::option::Option<unsafe extern "C" fn(arg1: *mut JSPrincipals) -> bool>,
    }

    #[repr(C)]
    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct JobQueueTraps {
        pub getHostDefinedData: ::std::option::Option<
            unsafe extern "C" fn(
                queue: *const std::os::raw::c_void,
                cx: *mut JSContext,
                data: MutableHandle<*mut JSObject>,
            ) -> bool,
        >,
        pub enqueuePromiseJob: ::std::option::Option<
            unsafe extern "C" fn(
                queue: *const std::os::raw::c_void,
                cx: *mut JSContext,
                promise: HandleObject,
                job: HandleObject,
                allocationSite: HandleObject,
                hostDefinedData: HandleObject,
            ) -> bool,
        >,
        pub runJobs: ::std::option::Option<
            unsafe extern "C" fn(queue: *const std::os::raw::c_void, cx: *mut JSContext),
        >,
        pub empty: ::std::option::Option<
            unsafe extern "C" fn(queue: *const std::os::raw::c_void) -> bool,
        >,
        pub pushNewInterruptQueue: ::std::option::Option<
            unsafe extern "C" fn(
                aInterruptQueues: *mut std::os::raw::c_void,
            ) -> *const std::os::raw::c_void,
        >,
        pub popInterruptQueue: ::std::option::Option<
            unsafe extern "C" fn(
                aInterruptQueues: *mut std::os::raw::c_void,
            ) -> *const std::os::raw::c_void,
        >,
        pub dropInterruptQueues: ::std::option::Option<
            unsafe extern "C" fn(aInterruptQueues: *mut std::os::raw::c_void),
        >,
    }

    #[repr(C)]
    #[derive(Debug, Copy, Clone, PartialEq)]
    pub struct ProxyTraps {
        pub enter: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                action: BaseProxyHandler_Action,
                bp: *mut bool,
            ) -> bool,
        >,
        pub getOwnPropertyDescriptor: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                desc: MutableHandle<PropertyDescriptor>,
                isNone: *mut bool,
            ) -> bool,
        >,
        pub defineProperty: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                desc: Handle<PropertyDescriptor>,
                result: *mut ObjectOpResult,
            ) -> bool,
        >,
        pub ownPropertyKeys: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                props: MutableHandleIdVector,
            ) -> bool,
        >,
        pub delete_: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                result: *mut ObjectOpResult,
            ) -> bool,
        >,
        pub enumerate: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                props: MutableHandleIdVector,
            ) -> bool,
        >,
        pub getPrototypeIfOrdinary: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                isOrdinary: *mut bool,
                protop: MutableHandleObject,
            ) -> bool,
        >,
        pub getPrototype: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                protop: MutableHandleObject,
            ) -> bool,
        >,
        pub setPrototype: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                proto: HandleObject,
                result: *mut ObjectOpResult,
            ) -> bool,
        >,
        pub setImmutablePrototype: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                succeeded: *mut bool,
            ) -> bool,
        >,
        pub preventExtensions: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                result: *mut ObjectOpResult,
            ) -> bool,
        >,
        pub isExtensible: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                succeeded: *mut bool,
            ) -> bool,
        >,
        pub has: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                bp: *mut bool,
            ) -> bool,
        >,
        pub get: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                receiver: HandleValue,
                id: HandleId,
                vp: MutableHandleValue,
            ) -> bool,
        >,
        pub set: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                v: HandleValue,
                receiver: HandleValue,
                result: *mut ObjectOpResult,
            ) -> bool,
        >,
        pub call: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                args: *const CallArgs,
            ) -> bool,
        >,
        pub construct: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                args: *const CallArgs,
            ) -> bool,
        >,
        pub hasOwn: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                id: HandleId,
                bp: *mut bool,
            ) -> bool,
        >,
        pub getOwnEnumerablePropertyKeys: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                props: MutableHandleIdVector,
            ) -> bool,
        >,
        pub nativeCall: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                test: IsAcceptableThis,
                impl_: NativeImpl,
                args: CallArgs,
            ) -> bool,
        >,
        pub objectClassIs: ::std::option::Option<
            unsafe extern "C" fn(
                obj: HandleObject,
                classValue: ESClass,
                cx: *mut JSContext,
            ) -> bool,
        >,
        pub className: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
            ) -> *const std::os::raw::c_char,
        >,
        pub fun_toString: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                isToString: bool,
            ) -> *mut JSString,
        >,
        pub boxedValue_unbox: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                proxy: HandleObject,
                vp: MutableHandleValue,
            ) -> bool,
        >,
        pub defaultValue: ::std::option::Option<
            unsafe extern "C" fn(
                cx: *mut JSContext,
                obj: HandleObject,
                hint: JSType,
                vp: MutableHandleValue,
            ) -> bool,
        >,
        pub trace: ::std::option::Option<
            unsafe extern "C" fn(trc: *mut JSTracer, proxy: *mut JSObject),
        >,
        pub finalize: ::std::option::Option<
            unsafe extern "C" fn(cx: *mut GCContext, proxy: *mut JSObject),
        >,
        pub objectMoved: ::std::option::Option<
            unsafe extern "C" fn(proxy: *mut JSObject, old: *mut JSObject) -> usize,
        >,
        pub isCallable:
            ::std::option::Option<unsafe extern "C" fn(obj: *mut JSObject) -> bool>,
        pub isConstructor:
            ::std::option::Option<unsafe extern "C" fn(obj: *mut JSObject) -> bool>,
    }

    pub type RustDispatchToEventLoopCallback = ::std::option::Option<
        unsafe extern "C" fn(
            closure: *mut std::os::raw::c_void,
            ptr: *mut DispatchablePointer,
        ) -> bool,
    >;

    pub type WantToMeasure =
        ::std::option::Option<unsafe extern "C" fn(obj: *mut JSObject) -> bool>;

