[Exposed=Window]
interface MutablePrimitives {
  attribute boolean enabled;
  attribute double ratio;
  attribute unsigned long count;
  attribute boolean? optionalEnabled;
  attribute double? optionalRatio;
  attribute unsigned long? optionalCount;
  undefined ping();
  boolean isEnabled();
  double currentRatio();
  unrestricted double currentUnrestrictedRatio();
  unrestricted double? optionalUnrestrictedRatioResult();
  unrestricted float currentUnrestrictedFloat();
  unrestricted float? optionalUnrestrictedFloatResult();
  unsigned long currentCount();
  boolean accepts(boolean value);
  double add(double value);
  unrestricted double echoUnrestricted(unrestricted double value);
  unsigned long wrap(unsigned long value);
  byte echoByte(byte value);
  octet echoOctet(octet value);
  short echoShort(short value);
  unsigned short echoUnsignedShort(unsigned short value);
  long echoLong(long value);
  long long echoLongLong(long long value);
  unsigned long long echoUnsignedLongLong(unsigned long long value);
  float echoFloat(float value);
  unrestricted float echoUnrestrictedFloat(unrestricted float value);
  DOMString currentLabel();
  DOMString? optionalLabel();
  USVString currentUsvLabel();
  USVString? optionalUsvLabel();
  boolean? optionalEnabledResult();
  double? optionalRatioResult();
  unsigned long? optionalCountResult();
  byte signedByteResult();
  octet octetResult();
  short shortResult();
  unsigned short unsignedShortResult();
  long longResult();
  long long longLongResult();
  unsigned long long unsignedLongLongResult();
  float floatResult();
  float? nullableFloatResult();
  long long? nullableLongLongResult();
};
