"""Generates roves-js's `rust::wrappers2` list from mozjs's.

Usage: gen_wrappers2.py <mozjs src dir> <roves-js src dir> <out.rs>

mozjs builds `rust::wrappers2` (the `&mut JSContext` / Rust-handle wrappers) by running its
`wrap!` macro over `jsapi2_wrappers.in.rs` and `glue2_wrappers.in.rs`. roves-js reuses the
same macro and keeps the entries whose function it implements: the name must be reachable
as `crate::jsapi::NAME` (for `jsapi` entries) or `crate::glue::NAME` (for `glue` entries),
and must not already be written by hand in `rust.rs`'s `wrappers2` module.
"""

import os
import re
import sys

FN = re.compile(r"^\s*pub (?:unsafe )?(?:extern \"C\" )?fn (\w+)", re.M)


def read(path):
    return open(path, encoding="utf-8").read()


def defined(path):
    return set(FN.findall(read(path)))


def reexports(text, module):
    """Names re-exported with `pub use crate::<module>::{...}` / `::*` / `::Name`."""
    names = set()
    glob = False
    for match in re.finditer(r"pub use crate::(\w+)::(\{[^}]*\}|\*|\w+);", text):
        if match.group(1) != module:
            continue
        items = match.group(2)
        if items == "*":
            glob = True
        else:
            names.update(re.findall(r"\w+", items))
    return names, glob


def visible(src, module_file):
    """The function names a module (`jsapi.rs` / `glue.rs`) makes reachable."""
    text = read(os.path.join(src, module_file))
    names = defined(os.path.join(src, module_file))
    for module in ("jsapi_impl", "binding", "realm_impl", "api", "object", "native", "proxy", "typedarray_impl", "runtime_impl"):
        explicit, glob = reexports(text, module)
        path = os.path.join(src, module + ".rs")
        if glob:
            names |= defined(path)
        names |= explicit & defined(path)
    return names


def handwritten(src):
    text = read(os.path.join(src, "rust.rs"))
    start = text.index("pub mod wrappers2 {")
    return set(FN.findall(text[start:]))


def main():
    mozjs, src, out = sys.argv[1:]
    available = {"jsapi": visible(src, "jsapi.rs"), "glue": visible(src, "glue.rs")}
    manual = handwritten(src)
    kept = []
    skipped = 0
    for name in ("jsapi2_wrappers.in.rs", "glue2_wrappers.in.rs"):
        for line in read(os.path.join(mozjs, name)).splitlines():
            entry = re.match(r"wrap!\((\w+): pub fn (\w+)\(", line)
            if not entry:
                continue
            module, function = entry.groups()
            if function in available[module] and function not in manual:
                kept.append(line)
            else:
                skipped += 1
    with open(out, "w", encoding="utf-8", newline="\n") as output:
        output.write("// Generated by support/roves_js/gen_wrappers2.py from mozjs's wrapper lists:\n")
        output.write("// the entries roves-js implements. Do not edit by hand.\n")
        for line in kept:
            output.write(line + "\n")
    print(f"kept {len(kept)} wrappers, skipped {skipped}")


if __name__ == "__main__":
    main()
